typography_spectrum: 0.07591
color:
  brandColors:
    - '#ffffff'
    - '#1a95d1'
    - '#767271'
    - '#dcdadb'
    - '#57b4da'
  brandStrength: 0.22359960014000535
  lightness: 0.841661611571908
  saturation: 0.7072170861065388
  rhythmicContrast: 0.1625956215430051
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Exit Design
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Brand Strategy. Brand Design. UI/UX Design.
description: Energizing Brands. Jumpstarting Businesses.
purpose: []
