name: Exit Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8455214784480631
title: Brand Strategy. Brand Design. UI/UX Design.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a95d1'
    - '#767271'
    - '#dcdadb'
    - '#57b4da'
  brandStrength: 0.22359960014000535
  lightness: 0.841661611571908
  saturation: 0.7072170861065388
  rhythmicContrast: 0.1625956215430051
purpose: []
